apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary
    app: myapp  # Key value pairs
spec:
  containers: # List
    - name: myapp
      image: acru15.azurecr.io/hello-world-u13:latest
      ports:
        - containerPort: 80
